export const events = [
  {
    id: 1,
    title: "Web Development Workshop",
    location: "New York",
    date: "25 Jul 2023, Tue",
    time: "10:00 AM EDT",
    author: "Sarah Johnson",
    authorProfile: "",
    image: "",
    genres: ["Technology", "Web Development"],
    eventMode: "Online",
    dateAndTime: "Tue, Jul 25, 2023 10:00 AM",
    address: "123 Main St, New York, NY 10001",
    language: "English",
    fees: "30",
    publishedAt: "18 min",
  },
  {
    id: 2,
    title: "Cooking Class: Italian Cuisine",
    location: "Rome",
    date: "08 Aug 2023, Mon",
    time: "06:30 PM CEST",
    author: "Marco Rossi",
    authorProfile: "",
    image: "",
    genres: ["Food & Cooking", "Cultural"],
    eventMode: "Offline",
    dateAndTime: "Mon, Aug 8, 2023 06:30 PM",
    address: "Via delle Terme di Tito, 00184 Roma RM, Italy",
    language: "Italian",
    fees: "40",
    publishedAt: "48 min",
  },
  {
    id: 3,
    title: "Yoga Retreat",
    location: "Bali",
    date: "20 Sep 2023, Wed",
    time: "08:00 AM WITA",
    author: "Emily Lee",
    authorProfile: "",
    image: "",
    genres: ["Health & Wellness", "Spiritual"],
    eventMode: "Online",
    dateAndTime: "Wed, Sep 20, 2023 08:00 AM",
    address: "Jl. Raya Kedewatan, Ubud, Gianyar, Bali 80571, Indonesia",
    language: "English",
    fees: "60",
    publishedAt: "11 hrs",
  },
  {
    id: 4,
    title: "Painting Workshop",
    location: "Paris",
    date: "05 Oct 2023, Thu",
    time: "03:00 PM CEST",
    author: "Claire Dubois",
    authorProfile: "",
    image: "",
    genres: ["Art & Culture", "Creativity"],
    eventMode: "Online",
    dateAndTime: "Thu, Oct 5, 2023 03:00 PM",
    address: "8 Rue de la Grande Chaumière, 75006 Paris, France",
    language: "French",
    fees: "50",
    publishedAt: "23 hrs",
  },
  {
    id: 5,
    title: "Startup Funding Conference",
    location: "San Francisco",
    date: "18 Nov 2023, Sat",
    time: "09:30 AM PST",
    author: "Michael Adams",
    authorProfile: "",
    image: "",
    genres: ["Business", "Entrepreneurship"],
    eventMode: "Offline",
    dateAndTime: "Sat, Nov 18, 2023 09:30 AM",
    address: "500 Howard St, San Francisco, CA 94105",
    language: "English",
    fees: "Free",
    publishedAt: "1 day",
  },
  {
    id: 6,
    title: "Photography Exhibition",
    location: "London",
    date: "02 Dec 2023, Sat",
    time: "11:00 AM GMT",
    author: "Sophie Turner",
    authorProfile: "",
    image: "",
    genres: ["Art & Culture", "Photography"],
    eventMode: "Offline",
    dateAndTime: "Sat, Dec 2, 2023 11:00 AM",
    address: "Southbank Centre, Belvedere Rd, Bishop's, London SE1 8XX, UK",
    language: "English",
    fees: "20",
    publishedAt: "2 days",
  },
  {
    id: 7,
    title: "Music Festival",
    location: "Madrid",
    date: "14 Jan 2024, Sat",
    time: "04:00 PM CST",
    author: "Alex Ramirez",
    authorProfile: "",
    image: "",
    genres: ["Music", "Festival"],
    eventMode: "Online",
    dateAndTime: "Sat, Jan 14, 2024 04:00 PM",
    address: "Zilker Park, 2100 Barton Springs Rd, Austin, TX 78704",
    language: "Spanish",
    fees: "75",
    publishedAt: "3 days",
  },
  {
    id: 8,
    title: "Fitness Bootcamp",
    location: "Sydney",
    date: "27 Feb 2024, Mon",
    time: "07:00 AM AEDT",
    author: "Emma Wilson",
    authorProfile: "",
    image: "",
    genres: ["Health & Wellness", "Fitness"],
    eventMode: "Online",
    dateAndTime: "Mon, Feb 27, 2024 07:00 AM",
    address: "33 Cross St, Double Bay NSW 2028, Australia",
    language: "English",
    fees: "45",
    publishedAt: "4 days",
  },
  {
    id: 9,
    title: "Science Fiction Book Club",
    location: "Toronto",
    date: "10 Mar 2024, Sat",
    time: "03:30 PM EST",
    author: "David Chen",
    authorProfile: "",
    image: "",
    genres: ["Literature", "Science Fiction"],
    eventMode: "Online",
    dateAndTime: "Sat, Mar 10, 2024 03:30 PM",
    address: "123 Yonge St, Toronto, ON M5C 1W4, Canada",
    language: "English",
    fees: "Free",
    publishedAt: "5 days",
  },
  {
    id: 10,
    title: "Digital Marketing Conference",
    location: "Singapore",
    date: "22 Apr 2024, Sun",
    time: "10:00 AM SGT",
    author: "Jennifer Tan",
    authorProfile: "",
    image: "",
    genres: ["Marketing", "Digital"],
    eventMode: "Offline",
    dateAndTime: "Sun, Apr 22, 2024 10:00 AM",
    address: "Marina Bay Sands, 10 Bayfront Ave, Singapore 018956",
    language: "English",
    fees: "65",
    publishedAt: "6 days",
  },
  {
    id: 11,
    title: "Web Design Workshop",
    location: "Brussels",
    date: "16 Jun 2023, Sat",
    time: "02:00 PM ETD",
    author: "Robert Fox",
    authorProfile: "",
    image: "",
    genres: ["Technology", "Movies", "Games"],
    eventMode: "Online",
    dateAndTime: "Thu, Mar 9, 2023 02:00 PM-United State Of America Time",
    address: "310 S. Main, Floor 12Salt Lake City, UT 84101",
    language: "English",
    fees: "50",
    publishedAt: "7 days",
  },
];
